name: VaultApp
options:
  bundleIdPrefix: com.yourname
targets:
  VaultApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - VaultApp/Sources
      - VaultApp/Resources
    info:
      path: VaultApp/Info.plist
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: VaultApp/Sources/VaultBridge.h
      # Force the linker to look exactly in the Libs folder we created
      LIBRARY_SEARCH_PATHS: 
        - $(inherited) 
        - "$(PROJECT_DIR)/VaultApp/Libs"
      OTHER_LDFLAGS: 
        - $(inherited) 
        - "-lvault_core"
      ENABLE_BITCODE: NO